apiVersion: v1
kind: Service
metadata:
  name: event-recommendation-service
spec:
  selector:
    app: event-recommendation
  ports:
    - protocol: TCP
      port: 8081
      targetPort: 8081
  type: LoadBalancer
