apiVersion: apps/v1
kind: Deployment
metadata:
  name: event-recommendation
spec:
  replicas: 2
  selector:
    matchLabels:
      app: event-recommendation
  template:
    metadata:
      labels:
        app: event-recommendation
    spec:
      containers:
        - name: event-recommendation
          image: eventregistry.azurecr.io/event-recommendation:latest
          ports:
            - containerPort: 8081
